### ISSUE TITLE
Quote breaks briefing

### ISSUE THREAD

**Issue by DarkMessiah27** [FakeMessiah27/AwesomeAmazingBriefingMaker2000#1]
Putting an uneven number of quotes in any textbox can break the briefing. Arma interprets them as the opening of a string. With an uneven number of quotes, a string is opened but never closed.

**Comment by Drofseh** [comment]
I think the simplest solution to this might be to just replace any double quote characters with single quotes before saving the text.

**Comment by DarkMessiah27** [comment]
The single quotes also break it unfortunately. I think what I'll do is simple count the quotes in each line of text, which should be simple enough. If the number if uneven, I'll add "/'" to the end of the line.

**Comment by Drofseh** [comment]
That's strange, single quotes inside the string should be fine as long as the string itself uses double quotes.
They become part of the string.
For example `"Thomas 'Tom' Brauer"` is a valid string in SQF.

**Comment by DarkMessiah27** [comment]
Resolved ages ago, forgot to close
